require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PalabrasController do

  # This should return the minimal set of attributes required to create a valid
  # Palabra. As you add validations to Palabra, be sure to
  # update the return value of this method accordingly.

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PalabrasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all palabras as @palabras" do
      palabra = FactoryGirl.create(:palabra)
      get :index, {}, valid_session
      #assigns(:palabras).should eq([palabra])
    end
  end

  describe "GET show" do
    it "assigns the requested palabra as @palabra" do
      palabra = FactoryGirl.create(:palabra)
      get :show, {:id => palabra.to_param}, valid_session
      assigns(:palabra).should eq(palabra)
    end
  end

  describe "GET new" do
    it "assigns a new palabra as @palabra" do
      get :new, {}, valid_session
      assigns(:palabra).should be_a_new(Palabra)
    end
  end

  describe "GET edit" do
    it "assigns the requested palabra as @palabra" do
      palabra = FactoryGirl.create(:palabra)
      get :edit, {:id => palabra.to_param}, valid_session
      assigns(:palabra).should eq(palabra)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Palabra" do
        palabra = FactoryGirl.build(:palabra)
        expect {
          post :create, {:palabra => palabra.attributes}, valid_session
        }.to change(Palabra, :count).by(1)
      end

      it "assigns a newly created palabra as @palabra" do
        palabra = FactoryGirl.build(:palabra)
        post :create, {:palabra => palabra.attributes}, valid_session
        assigns(:palabra).should be_a(Palabra)
        assigns(:palabra).should be_persisted
      end

      it "redirects to the created palabra" do
        palabra = FactoryGirl.build(:palabra)
        post :create, {:palabra => palabra.attributes}, valid_session
        response.should redirect_to(Palabra.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved palabra as @palabra" do
        # Trigger the behavior that occurs when invalid params are submitted
        Palabra.any_instance.stub(:save).and_return(false)
        post :create, {:palabra => {}}, valid_session
        assigns(:palabra).should be_a_new(Palabra)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Palabra.any_instance.stub(:save).and_return(false)
        post :create, {:palabra => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested palabra" do
        palabra = FactoryGirl.create(:palabra)
        # Assuming there are no other palabras in the database, this
        # specifies that the Palabra created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Palabra.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => palabra.to_param, :palabra => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested palabra as @palabra" do
        palabra = FactoryGirl.create(:palabra)
        palabra1 = FactoryGirl.build(:palabra)
        put :update, {:id => palabra.to_param, :palabra => palabra1}, valid_session
        assigns(:palabra).should eq(palabra)
      end

      it "redirects to the palabra" do
        palabra = FactoryGirl.create(:palabra)
        palabra1 = FactoryGirl.build(:palabra)
        put :update, {:id => palabra.to_param, :palabra => palabra1}, valid_session
        response.should redirect_to(palabra)
      end
    end

    describe "with invalid params" do
      it "assigns the palabra as @palabra" do
        palabra = FactoryGirl.create(:palabra)
        # Trigger the behavior that occurs when invalid params are submitted
        Palabra.any_instance.stub(:save).and_return(false)
        put :update, {:id => palabra.to_param, :palabra => {}}, valid_session
        assigns(:palabra).should eq(palabra)
      end

      it "re-renders the 'edit' template" do
        palabra = FactoryGirl.create(:palabra)
        # Trigger the behavior that occurs when invalid params are submitted
        Palabra.any_instance.stub(:save).and_return(false)
        put :update, {:id => palabra.to_param, :palabra => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested palabra" do
      palabra = FactoryGirl.create(:palabra)
      expect {
        delete :destroy, {:id => palabra.to_param}, valid_session
      }.to change(Palabra, :count).by(-1)
    end

    it "redirects to the palabras list" do
      palabra = FactoryGirl.create(:palabra)
      delete :destroy, {:id => palabra.to_param}, valid_session
      response.should redirect_to(palabras_url)
    end
  end

end
