require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SignificadosController do

  # This should return the minimal set of attributes required to create a valid
  # Significado. As you add validations to Significado, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { palabra: "ka\'avi" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SignificadosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all significados as @significados" do
      significado = Significado.create! valid_attributes
      get :index, {}, valid_session
      assigns(:significados).should eq([significado])
    end
  end

  describe "GET show" do
    it "assigns the requested significado as @significado" do
      significado = Significado.create! valid_attributes
      get :show, {:id => significado.to_param}, valid_session
      assigns(:significado).should eq(significado)
    end
  end

  describe "GET new" do
    it "assigns a new significado as @significado" do
      get :new, {}, valid_session
      assigns(:significado).should be_a_new(Significado)
    end
  end

  describe "GET edit" do
    it "assigns the requested significado as @significado" do
      significado = Significado.create! valid_attributes
      get :edit, {:id => significado.to_param}, valid_session
      assigns(:significado).should eq(significado)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Significado" do
        expect {
          post :create, {:significado => valid_attributes}, valid_session
        }.to change(Significado, :count).by(1)
      end

      it "assigns a newly created significado as @significado" do
        post :create, {:significado => valid_attributes}, valid_session
        assigns(:significado).should be_a(Significado)
        assigns(:significado).should be_persisted
      end

      it "redirects to the created significado" do
        post :create, {:significado => valid_attributes}, valid_session
        response.should redirect_to(Significado.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved significado as @significado" do
        # Trigger the behavior that occurs when invalid params are submitted
        Significado.any_instance.stub(:save).and_return(false)
        post :create, {:significado => {}}, valid_session
        assigns(:significado).should be_a_new(Significado)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Significado.any_instance.stub(:save).and_return(false)
        post :create, {:significado => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested significado" do
        significado = Significado.create! valid_attributes
        # Assuming there are no other significados in the database, this
        # specifies that the Significado created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Significado.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => significado.to_param, :significado => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested significado as @significado" do
        significado = Significado.create! valid_attributes
        put :update, {:id => significado.to_param, :significado => valid_attributes}, valid_session
        assigns(:significado).should eq(significado)
      end

      it "redirects to the significado" do
        significado = Significado.create! valid_attributes
        put :update, {:id => significado.to_param, :significado => valid_attributes}, valid_session
        response.should redirect_to(significado)
      end
    end

    describe "with invalid params" do
      it "assigns the significado as @significado" do
        significado = Significado.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Significado.any_instance.stub(:save).and_return(false)
        put :update, {:id => significado.to_param, :significado => {}}, valid_session
        assigns(:significado).should eq(significado)
      end

      it "re-renders the 'edit' template" do
        significado = Significado.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Significado.any_instance.stub(:save).and_return(false)
        put :update, {:id => significado.to_param, :significado => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested significado" do
      significado = Significado.create! valid_attributes
      expect {
        delete :destroy, {:id => significado.to_param}, valid_session
      }.to change(Significado, :count).by(-1)
    end

    it "redirects to the significados list" do
      significado = Significado.create! valid_attributes
      delete :destroy, {:id => significado.to_param}, valid_session
      response.should redirect_to(significados_url)
    end
  end

end
